# Site settings
title: Code Notes
email: qbi11y@gmail.com
description: "Coding is a bitch! I do shit and get passed it for the moment! The problem is a few weeks later, I need to do it again! My goal is to capture those things that give me trouble so that I can look back at my digital notebook!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: iam_babyhuey
github_username:  qbi11y

# Build settings
markdown: kramdown
permalink: pretty
